// Generated by CoffeeScript 1.6.2
(function() {
  document.getElementById("color").focus();

  $(document).keydown(function(evt) {
    var cL, colr, i, _i, _len;

    if (evt.keyCode === 13) {
      colr = $("#color").val().toUpperCase();
      cL = colr.match(/./g);
      for (_i = 0, _len = cL.length; _i < _len; _i++) {
        i = cL[_i];
        if (cL[i] !== '#' && (cL[i] < '0' || cL[i] > '9' && cL[i] < 'A' || cL[i] > 'F')) {
          break;
        }
      }
      return document.body.style.backgroundColor = (colr.charAt(0) !== '#' && i >= cL.length && '#' || '') + colr;
    }
  });

}).call(this);

/*
//@ sourceMappingURL=script.map
*/